# Generated by Django 4.2.20 on 2025-03-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atrium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevPlanGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NS', 'Onboarding'), ('IP', '1:1 sessions'), ('C', 'Complete'), ('A', 'Impact Assessment')], default='NS', max_length=2)),
                ('dev_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atrium.developmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Atrium',
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atrium.user'),
        ),
    ]
